### ISSUE TITLE
PCRE backtrack-limit hit on huge HTML

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/seo-override#43]
On a huge HTML page I get the `preg_replace` error **PREG_BACKTRACK_LIMIT_ERROR**.

https://www.php.net/manual/en/pcre.configuration.php#ini.pcre.backtrack-limit

Following this error, `preg_replace` return `null` and we get a fatal error because the method signature expect a string.

> Return value of Joli\SeoOverride\SeoManager::overrideHtml() must be of the type string, null returned

**Comment by MatTheCat** [comment]
Il y a eu [une issue similaire sur le parser YAML de Symfony](https://github.com/symfony/symfony/issues/20411) qui s'est résolue avec l'utilisation d'un [quantifieur possessif](https://www.regular-expressions.info/possessive.html).
